# Generated by Django 3.2 on 2021-08-06 13:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("channel", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=10)),
                ("os", models.CharField(max_length=15)),
                ("impressions", models.IntegerField()),
                ("clicks", models.IntegerField()),
                ("installs", models.IntegerField()),
                ("spend", models.FloatField()),
                ("revenue", models.FloatField()),
            ],
        ),
    ]
